macro(convert_bool var)
  if(${var})
      set(${var} 1)
  else()
      set(${var} 0)
  endif()
endmacro()

macro(xkoption var desc default)
    option(${var} "${desc}" ${default})
    convert_bool(var)
endmacro()
